//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntalTimmar
    {
        public int AntalTimmarID { get; set; }
        public int Adm { get; set; }
        public int FörsMark { get; set; }
        public int UtvFörv { get; set; }
        public int Drift { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
