//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseModelContainer : DbContext
    {
        public DatabaseModelContainer()
            : base("name=DatabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prognos> Prognos { get; set; }
        public virtual DbSet<Intäktsbudget> Intäktsbudget { get; set; }
        public virtual DbSet<Kund> Kund { get; set; }
        public virtual DbSet<KundKategori> KundKategori { get; set; }
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<AntalTimmar> AntalTimmar { get; set; }
        public virtual DbSet<Avdelning> Avdelning { get; set; }
        public virtual DbSet<Produktgrupp> Produktgrupp { get; set; }
        public virtual DbSet<Produktkategori> Produktkategori { get; set; }
        public virtual DbSet<Aktivitet> Aktivitet { get; set; }
        public virtual DbSet<Direktkostnad> Direktkostnad { get; set; }
        public virtual DbSet<Konto> Konto { get; set; }
        public virtual DbSet<schablonkostnad> schablonkostnad { get; set; }
    }
}
