//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intäktsbudget
    {
        public int IntäktsbudgetID { get; set; }
        public bool Låst { get; set; }
        public decimal Avtal { get; set; }
        public bool GradA { get; set; }
        public decimal Tillägg { get; set; }
        public bool GradT { get; set; }
        public decimal Budget { get; set; }
        public int Tim { get; set; }
        public string Kommentar { get; set; }
    
        public virtual Prognos Prognos { get; set; }
        public virtual Kund Kund { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
