//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.AntalTimmar = new HashSet<AntalTimmar>();
            this.Produkt = new HashSet<Produkt>();
            this.Avdelning = new HashSet<Avdelning>();
        }
    
        public int PersonalID { get; set; }
        public string PersonNr { get; set; }
        public string Namn { get; set; }
        public int Månadslön { get; set; }
        public int Sysselsättningsgrad { get; set; }
        public int Vakansavdrag { get; set; }
        public string Lösenord { get; set; }
        public string Behörighet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AntalTimmar> AntalTimmar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkt> Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avdelning> Avdelning { get; set; }
    }
}
